### ISSUE TITLE
Show tasks and provide the ability to kill/purge a task and filter by transaction ID

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/vscode-extension-for-cics#110]
Developers may wish to list tasks for their transactions, view attributes, and kill/purge ones.  This is useful if their task is hanging onto a resource or runaway and they want to end it.  

The CICS CLI allows you to list tasks with `zowe cics get resource CICSTASK --criteria "TRANID=C*" --rfh --rff tranid runstatus priority --rft table` so the table is there.

The base CLI doesn't allow tasks to be purged so issue https://github.com/zowe/zowe-cli-cics-plugin/issues/109 in the CLI repo tracks that

**Comment by Joe-Winchester** [comment]
CICS Explorer options are  Purge ->. Kill,   Purge,  Force Purge.

**Comment by JeffinSiby** [comment]
Closed by [032ded2](https://github.com/zowe/vscode-extension-for-cics/commit/032ded2a8c78a8f996fc169fa257d4df82863389). Users can purge, force purge and kill a running task and also filter by transaction ID
