### ISSUE TITLE
Provide the ability to list resources of a type across all regions in a plex

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/vscode-extension-for-cics#113]
If a user wants to perform an action over all instances of a region in multiple regions in a plex this would allow them to navigate from
```
PLEX
   Program. (PROG1234*)
       PROG1234 - Region(REG1)
       PROG1234 - Region(REG2)
       PROG1234 - Region(REG3)
```
and from there multi select all of the program and perform a newcopy
Currently the way to do this is 
```
PLEX
    REG1
        Program (PROG1234*)
            PROG1234
    REG2
         Program (PROG1234*)
             PROG1234
    REG3
         Program (PROG1234*)
             PROG1234
```
The problem with the above (current view) is that you have to ctrl+click to get all 3 programs, and it takes more vertical room to show the programs in the regions (10 lines rather than 5 lines).

**Comment by JeffinSiby** [comment]
Closed by 66b5d0bd6a4461b41cff51329771c811e95dc378

All programs under a plex:

![allProgramsUnderPlex](https://user-images.githubusercontent.com/57257691/145016891-49a9d055-38a3-4dea-8532-6f3bed31e08f.gif)

View more resources feature:

![load800more](https://user-images.githubusercontent.com/57257691/145016785-f1e97488-95bb-4129-9a11-ea07a442c602.gif)
