### ISSUE TITLE
Search text for filter is cleared when create a new filter option is clicked

### ISSUE THREAD

**Issue by JeffinSiby** [zowe/vscode-extension-for-cics#216]
When a user clicks the search button to apply a filter, they are presented with an input box. If they type the search criteria in and then click the create a new filter option, their original input is cleared and they have to type in the search criteria again.

The search filter should be carried through if the user clicks the option to create a new filter

**Comment by Rajpreetgill** [comment]
This issue was fixed here: https://github.com/zowe/vscode-extension-for-cics/pull/258.
