### ISSUE TITLE
Project does not build on Linux

### ISSUE THREAD

**Issue by zFernand0** [zowe/vscode-extension-for-cics#221]
Seems like `src/commands/filterAllProgramsCommand.ts` imports `../utils/filterUtils` but the filename is `FilterUtils`
Tested it and changing the file back to `filterUtils will solve all cases 😋

**Comment by JeffinSiby** [comment]
Thanks @zFernand0! Did you pull the latest changes on the [main](https://github.com/zowe/vscode-extension-for-cics) branch? I think [8993c81](https://github.com/zowe/vscode-extension-for-cics/commit/8993c816ba7da2c6fd127685599269f3cb3facf2) might address this issue, but if not let me know 🙂

**Comment by zFernand0** [comment]
you are correct! 😋 
I was on the `next` branch.
That's my bad.
Closing
