### ISSUE TITLE
Add a limit to the resource trees

### ISSUE THREAD

**Issue by JeffinSiby** [zowe/vscode-extension-for-cics#225]
If a user requests for a search that results in 500+ resource results, the combined resources trees, i.e. the `All` resource trees, show the first 500 instances of that resource and displays a `View More` tree item which the user can click to fetch more resources. 

Implement the same feature for Programs, Local Transactions, Local Files and Tasks

**Comment by AdarshdeepCheema** [comment]
This is already implemented
<img width="777" alt="Screen Shot 2022-07-06 at 11 05 12 AM" src="https://user-images.githubusercontent.com/57364561/177582682-693c3a1c-c05f-4ef1-89c8-bf68962de146.png">
