### ISSUE TITLE
Allow users to set the max amount of resources shown in an 'All' resource tree

### ISSUE THREAD

**Issue by JeffinSiby** [zowe/vscode-extension-for-cics#230]
Currently, if a filter on an 'All' resource tree results in over 500 results, the max number of results shown is 500 and the user can click the view x more text tree item to fetch more results.

Users should be able to modify this max limit in Settings (UI)

**Comment by Rajpreetgill** [comment]
This issue was fixed here: https://github.com/zowe/vscode-extension-for-cics/pull/242.
