### ISSUE TITLE
Test the CICS extension on Eclipse Che

### ISSUE THREAD

**Issue by AndrewTwydell** [zowe/vscode-extension-for-cics#64]
we should check if Theia is being used when showing attributes or creating a profile, and use alternate methods if that is the case.

**Comment by jellypuno** [comment]
So webviews are not really working in Theia? I am also interested in this research. Please keep me posted.

**Comment by jellypuno** [comment]
Initial Fix: 
- Add a check to switch between webview and dialogs
- More research needed between theia and eclipse che

**Comment by zFernand0** [comment]
We will get back to this around the same time as
- https://github.com/zowe/vscode-extension-for-zowe/issues/479
