### ISSUE TITLE
Display error response for failed actions (such as NewCopy)

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/vscode-extension-for-cics#89]
NewCopy a program where the user doesn't have permission, e.g.
IOSTREAM
CICS Explorer returns a response ` CNX0591E: EXEC CICS command(SET PROGRAM) RESP(IOERR) RESP2(8)`

**Comment by JeffinSiby** [comment]
Fixed with commit f35fafb9a954da1b783ba10a1716342f96eb2c6c
